//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVot.Models
{
    using System;
    using System.Collections.Generic;

    public partial class GioHang
    {
        public int MaVot { get; set; } // Mã sản phẩm
        public string TenVot { get; set; } // Tên sản phẩm
        public decimal GiaBan { get; set; } // Giá bán
        public int SoLuong { get; set; } // Số lượng sản phẩm
        public decimal ThanhTien
        {
            get { return GiaBan * SoLuong; }
        }
    }
}
