//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public int MaKho { get; set; }
        public string MaVot { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    
        public virtual Vot Vot { get; set; }
    }
}
